version: '3'

services:
  web:
    build:
      context: .
    command: npm start
    ports:
      - "80:80"
    volumes:
      - .:/code
      - /code/node_modules
    devices:
      - /dev/mem:/dev/mem
    privileged: true
